CA-20 [API] 게시판 Class Diagram 설계 및 Entity 생성
Codepied/Codepied-API pull request #51
Opened 2023-02-09 06:26 UTC by junY97

<html>
<body>
<h3 dir="auto" style="box-sizing: border-box; margin-top: 0px !important; margin-bottom: 16px; font-size: 1.25em; font-weight: var(--base-text-weight-semibold, 600); line-height: 1.25;">Overview</h3>

항목 | 내용
-- | --
Review Order | 1
Review Date | 2023.02.12
Reviewer | 아이비스

<h3 dir="auto" style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 1.25em; font-weight: var(--base-text-weight-semibold, 600); line-height: 1.25;">Result (PASS/FAIL/FOLLOWUP)</h3><table role="table" style="box-sizing: border-box; border-spacing: 0px; border-collapse: collapse; margin-top: 0px; margin-bottom: 0px !important; display: block; width: max-content; max-width: 100%; overflow: auto;"><thead style="box-sizing: border-box;"><tr style="box-sizing: border-box; background-color: var(--color-canvas-default); border-top: 1px solid var(--color-border-muted);"><th style="box-sizing: border-box; padding: 6px 13px; font-weight: var(--base-text-weight-semibold, 600); border: 1px solid var(--color-border-default);">Result</th><th align="left" style="box-sizing: border-box; padding: 6px 13px; font-weight: var(--base-text-weight-semibold, 600); border: 1px solid var(--color-border-default);">Comment</th></tr></thead><tbody style="box-sizing: border-box;"><tr style="box-sizing: border-box; background-color: var(--color-canvas-default); border-top: 1px solid var(--color-border-muted);"><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--color-border-default); color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"></td><br class="Apple-interchange-newline">
</body>
</html>

2023-02-09 07:42 UTC, Aivyss requested changes
수정 후 재요청 할 것.

2023-02-09 07:42 UTC, Aivyss commented on src/docs/rds/schema.sql
> +      UUID 		        VARCHAR(38)         NOT NULL,
타입을 UUID로 변경 이거 외에 uuid를 varchar로 한것들 전부.

2023-02-09 07:42 UTC, Aivyss commented on src/docs/rds/schema.sql
> +   UUID 		        VARCHAR(38)         NOT NULL,
타입 uuid로 변경

2023-02-09 07:42 UTC, Aivyss commented on src/main/kotlin/com/codepied/api/api/board/domain/Board.kt
> +    @Column(name = "UUID", nullable = false, length = 34)
updateable 없음. length 필요 없음.

2023-02-09 07:42 UTC, Aivyss commented on src/main/kotlin/com/codepied/api/api/board/domain/Thread.kt
> +    @Column(name = "UUID", nullable = false, updatable = false, length = 38)
length 필요 없음.

2023-02-09 07:42 UTC, Aivyss commented on src/main/kotlin/com/codepied/api/api/board/domain/ThreadScore.kt
> +    val score: Long,
val은 수정 불가인데 updatable이 true임.

2023-02-09 07:42 UTC, Aivyss commented on src/main/kotlin/com/codepied/api/api/board/domain/BoardManager.kt
> +    val user: User,
updatable = false

2023-02-09 07:42 UTC, Aivyss commented on src/main/kotlin/com/codepied/api/api/board/domain/Thread.kt
> +    val title: String,
val -> var

2023-02-09 07:42 UTC, Aivyss commented on src/main/kotlin/com/codepied/api/api/board/domain/Thread.kt
> +    val anonymous: Boolean,
updatable = false

2023-02-09 07:42 UTC, Aivyss commented on src/main/kotlin/com/codepied/api/api/board/domain/ThreadScore.kt
> +    @JoinColumn(name = "THREAD_VIEW_KEY", nullable = false, updatable = true)
updatable = false

2023-02-09 07:42 UTC, Aivyss commented on src/main/kotlin/com/codepied/api/api/board/domain/ThreadScore.kt
> +    @JoinColumn(name = "THREAD_VOTE_KEY", nullable = false, updatable = true)
updatable = false

2023-02-10 01:08 UTC, junY97 commented on src/main/kotlin/com/codepied/api/api/board/domain/BoardManager.kt
> +    val user: User,
보드 매니저의 유저는 다른 유저로 바뀔수있다는 생각에 updatetable 트루로 걸었음

2023-02-10 01:09 UTC, junY97 commented on src/docs/rds/schema.sql
> +      UUID 		        VARCHAR(38)         NOT NULL,
확인

2023-02-10 01:09 UTC, junY97 commented on src/docs/rds/schema.sql
> +   UUID 		        VARCHAR(38)         NOT NULL,
확인

2023-02-10 01:09 UTC, junY97 commented on src/main/kotlin/com/codepied/api/api/board/domain/Board.kt
> +    @Column(name = "UUID", nullable = false, length = 34)
확인

2023-02-10 01:09 UTC, junY97 commented on src/main/kotlin/com/codepied/api/api/board/domain/Thread.kt
> +    @Column(name = "UUID", nullable = false, updatable = false, length = 38)
확인

2023-02-10 01:41 UTC, junY97 commented on src/main/kotlin/com/codepied/api/api/board/domain/ThreadScore.kt
> +    val score: Long,
확인

2023-02-10 01:41 UTC, junY97 commented on src/main/kotlin/com/codepied/api/api/board/domain/Thread.kt
> +    val title: String,
확인

2023-02-10 01:42 UTC, junY97 commented on src/main/kotlin/com/codepied/api/api/board/domain/Thread.kt
> +    val anonymous: Boolean,
익명은 유저가 언제든 익명으로 전환가능하므로 updatable true로 지정

2023-02-10 01:42 UTC, junY97 commented on src/main/kotlin/com/codepied/api/api/board/domain/ThreadScore.kt
> +    @JoinColumn(name = "THREAD_VIEW_KEY", nullable = false, updatable = true)
확인

2023-02-10 01:42 UTC, junY97 commented on src/main/kotlin/com/codepied/api/api/board/domain/ThreadScore.kt
> +    @JoinColumn(name = "THREAD_VOTE_KEY", nullable = false, updatable = true)
확인

2023-02-10 03:32 UTC, Aivyss requested changes

2023-02-10 03:32 UTC, Aivyss commented on src/main/kotlin/com/codepied/api/api/board/domain/Board.kt
> +    val uuid: UUID,
updatable = false

2023-02-10 03:32 UTC, Aivyss commented on src/main/kotlin/com/codepied/api/api/board/domain/BoardManager.kt
> +    val id :Long,
val id: Long,

2023-02-10 03:32 UTC, Aivyss commented on src/main/kotlin/com/codepied/api/api/board/domain/Board.kt
> +    val thread: MutableList<Thread> = mutableListOf()
생각해보니 빼자. 게시글 수 늘어나면 메모리 감당이 안됨.

2023-02-10 03:32 UTC, Aivyss commented on src/main/kotlin/com/codepied/api/api/board/domain/ThreadComment.kt
> +)
코멘트 입력 content는 어디에 있음...?

2023-02-10 03:32 UTC, Aivyss commented on src/main/kotlin/com/codepied/api/api/board/domain/ThreadFile.kt
> +    val user: User,
스레드 파일 자체가 의미가 있나 싶고 있다고 하더라도 user는 필요없음 올린사람이 Thread에 저장된 user일테니.

2023-02-10 03:32 UTC, Aivyss commented on src/main/kotlin/com/codepied/api/api/board/domain/ThreadScore.kt
> +    val threadVote: ThreadVote,
vote가 왜 1개지? MutableList여야 할걸?

2023-02-10 03:32 UTC, Aivyss commented on src/main/kotlin/com/codepied/api/api/board/domain/ThreadScore.kt
> +    val threadView: ThreadView,
뷰도 MutableList여야할걸?

2023-02-11 02:12 UTC, Aivyss requested changes

2023-02-11 02:12 UTC, Aivyss commented on src/main/kotlin/com/codepied/api/api/board/domain/ThreadVote.kt
> +    val recommend: Boolean,
bar, updatable=true

2023-02-12 03:04 UTC, junY97 commented on src/main/kotlin/com/codepied/api/api/board/domain/Board.kt
> +    val uuid: UUID,
확인

2023-02-12 03:04 UTC, junY97 commented on src/main/kotlin/com/codepied/api/api/board/domain/BoardManager.kt
> +    val id :Long,
val id long??

2023-02-12 03:06 UTC, junY97 commented on src/main/kotlin/com/codepied/api/api/board/domain/Board.kt
> +    val thread: MutableList<Thread> = mutableListOf()
확인

2023-02-12 03:08 UTC, Aivyss commented on src/main/kotlin/com/codepied/api/api/board/domain/BoardManager.kt
> +    val user: User,
그럼 바뀌어서 없어진 유저를 delete해야지 외래키를 바꾸는건 아니란다.

2023-02-12 03:11 UTC, Aivyss commented on src/main/kotlin/com/codepied/api/api/board/domain/Thread.kt
> +    val anonymous: Boolean,
false로 할것

2023-02-12 03:13 UTC, Aivyss commented on src/main/kotlin/com/codepied/api/api/board/domain/Thread.kt
> +    val anonymous: Boolean,
false로 할것

2023-02-12 03:14 UTC, Aivyss commented on src/main/kotlin/com/codepied/api/api/board/domain/BoardManager.kt
> +    val id :Long,
띄어쓰기가 잘못돼있음

2023-02-12 05:23 UTC, junY97 commented on src/main/kotlin/com/codepied/api/api/board/domain/ThreadComment.kt
> +)
추가 완료

2023-02-12 05:24 UTC, junY97 commented on src/main/kotlin/com/codepied/api/api/board/domain/ThreadFile.kt
> +    val user: User,
완료

2023-02-12 05:28 UTC, junY97 commented on src/main/kotlin/com/codepied/api/api/board/domain/ThreadScore.kt
> +    val threadVote: ThreadVote,
삭제완료
thread score에서 view나 vote를 불러올 필요없음으로 판단

2023-02-12 05:28 UTC, junY97 commented on src/main/kotlin/com/codepied/api/api/board/domain/ThreadScore.kt
> +    val threadView: ThreadView,
삭제완료
thread score에서 view나 vote를 불러올 필요없음으로 판단

2023-02-12 05:29 UTC, junY97 commented on src/main/kotlin/com/codepied/api/api/board/domain/ThreadVote.kt
> +    val recommend: Boolean,
확인

2023-02-12 05:34 UTC, Aivyss requested changes

2023-02-12 05:34 UTC, Aivyss commented on src/main/kotlin/com/codepied/api/api/board/domain/ThreadScore.kt
> +    @Column(name = "THREAD_SCORE_KEY")
THREAD_KEY 외래키이자 기본키

2023-02-12 05:40 UTC, junY97 commented on src/main/kotlin/com/codepied/api/api/board/domain/ThreadScore.kt
> +    @Column(name = "THREAD_SCORE_KEY")
확인

2023-02-12 05:45 UTC, Aivyss commented on src/main/kotlin/com/codepied/api/api/board/domain/ThreadComment.kt
> +)
소문자네...

2023-02-12 05:47 UTC, Aivyss requested changes

2023-02-12 05:47 UTC, Aivyss commented on src/main/kotlin/com/codepied/api/api/board/domain/ThreadFile.kt
> +
개행 두번 돼있는데 개행없게, 다른 것도 다.

2023-02-12 06:44 UTC, Aivyss approved these changes
승인.

2023-02-12 06:44 UTC, merged