CA-42 [API] 게시판 생성 구현
Codepied/Codepied-API pull request #56
Opened 2023-02-17 05:05 UTC by junY97

### Overview

| 항목 | 내용 |
|--------------|:-------------|
| Review Order | 1 |
| Review Date | 2023.02.14 |
| Reviewer | Aivyss|

### Result (PASS/FAIL/FOLLOWUP)

| Result | Comment |
|--------------|:-------------|
|PASS |SUCCESS |

2023-02-17 12:03 UTC, Aivyss requested changes
레스트독 문서 안만들었음.

2023-02-17 12:03 UTC, Aivyss commented on src/test/kotlin/com/codepied/api/board/endpoint/BoardControllerTest.kt
> + *
이거 개행 두개는 대체 왜넣는겨? 다 그러던데 다 지우자

2023-02-20 01:54 UTC, Aivyss requested changes
테스트 케이스 부족

2023-02-20 01:54 UTC, Aivyss commented on src/test/kotlin/com/codepied/api/board/endpoint/BoardControllerTest.kt
> +
실패 케이스 테스트가 없음

2023-02-20 02:47 UTC, Aivyss requested changes

2023-02-20 02:47 UTC, Aivyss commented on src/main/kotlin/com/codepied/api/board/application/BoardService.kt
> +    fun createBoard(request: BoardCreate): BoardCreate {
이걸 왜 반환함? 필요 없음.

2023-02-20 02:49 UTC, Aivyss commented on src/main/kotlin/com/codepied/api/board/application/BoardService.kt
> +    fun createBoard(request: BoardCreate): BoardCreate {
반환 하더라도(정말 필요없음) parameter랑 내용이 같은 객체라 무의미함

2023-02-20 03:09 UTC, junY97 commented on src/test/kotlin/com/codepied/api/board/endpoint/BoardControllerTest.kt
> + *
확인

2023-02-20 08:21 UTC, junY97 commented on src/test/kotlin/com/codepied/api/board/endpoint/BoardControllerTest.kt
> +
확인

2023-02-20 08:21 UTC, junY97 commented on src/main/kotlin/com/codepied/api/board/application/BoardService.kt
> +    fun createBoard(request: BoardCreate): BoardCreate {
확인

2023-02-22 03:33 UTC, Aivyss approved these changes

2023-02-22 03:34 UTC, merged